### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by m4ster0wl** [cubetastic33/sakubun#9]
Hi, 

Sakubun looks exactly like what I'm looking for, but after specifying my known kanjis, I have 500 errors when I try to get a quiz or an essay.

Not sure if you are still maintaining the tool, but if you could fix the issue that'd be great 😊

Kr,
Simon

**Comment by cubetastic33** [comment]
Hey Simon!

Glad to know you find my tool useful! Yes, I do still maintain it - thanks
a lot for notifying me of the error! It should be fixed now. Feel free to
let me know if you have any feedback or other issues!

Best,
Aravind

**Comment by m4ster0wl** [comment]
Many thanks! 😊
